# -*- coding: utf-8 -*-
"""NGrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ttrij1P2cgC66F7DbAYMrS_4vmO9yYqW
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ankurzing/sentiment-analysis-for-financial-news")

print("Path to dataset files:", path)

import pandas as pd
import os

# The path variable contains the directory where the dataset files are downloaded
file_path = os.path.join(path, 'all-data.csv')

# Read the CSV file into a pandas DataFrame, specifying the encoding
df = pd.read_csv(file_path, encoding='latin-1')

# Display the head of the DataFrame
display(df.head(30))

"""# Begin Data Pre-Processing

## First we'll start by looking at the layout of the data
"""

df.info()
#4845 rows 2 columns

"""###preprocessing for NLP
I've taken a look at the data in excel and using df.head() and we find that the dataframe is made up of a column for the sentiment of the sentence and a column for the sentence itself.

Before tokenizing and subsequent n-gram generation and analysis we'll first create column headers, lowercase text for uniform tokenization, and remove common stop words that tend to clutter the data

we will then use NLTK for tokenization
"""

#create headers for columns
import pandas as pd

df.columns = ['sentiment', 'text']

print(df.head(10))

#lowercasing by simply using pandas
df['text'] = df['text'].str.lower()
print(df)

"""### Tokenization Using NLTK Library and Stop-Word Rework"""

#begin tokenization and stop word removal
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

resources = ["stopwords", "punkt", "punkt_tab"]

for resource in resources:
    try:
        nltk.data.find(f"{'corpora' if resource=='stopwords' else 'tokenizers'}/{resource}")
    except LookupError:
        nltk.download(resource)

def tokenize_text(text):
    stop_words = set(stopwords.words('english'))
    sentences = sent_tokenize(text)
    tokenized_sentences = []
    for sentence in sentences:
        words = word_tokenize(sentence)
        # Remove stop words
        filtered_words = [word for word in words if word.lower() not in stop_words]
        tokenized_sentences.append(filtered_words)
    return tokenized_sentences

df['tokenized_text'] = df['text'].apply(tokenize_text)

print(df.head())

"""#Task 1
Now that our text is preprocessed we can move onto n-gram generation and analysis

##N-Gram Generation
I found that there are manual ways to do this and functions native to NLTK to accomplish this. The manual way I found here: https://stackoverflow.com/questions/13423919/computing-n-grams-using-python

I use both techniques for learning sake
"""

#Manual
def find_ngrams(input_list, n):
  return zip(*[input_list[i:] for i in range(n)])

unigram_value = 1
bigram_value = 2
trigram_value = 3

# Flatten the list of lists in 'tokenized_text' before applying find_ngrams
df['manual_unigram'] = df['tokenized_text'].apply(lambda x: list(find_ngrams([word for sentence in x for word in sentence], unigram_value)))
df['manual_bigram'] = df['tokenized_text'].apply(lambda x: list(find_ngrams([word for sentence in x for word in sentence], bigram_value)))
df['manual_trigram'] = df['tokenized_text'].apply(lambda x: list(find_ngrams([word for sentence in x for word in sentence], trigram_value)))


print(df)

#n-gram generation with NLTK
from nltk.util import ngrams
from nltk.tokenize import word_tokenize # Import word_tokenize to flatten the list of lists

def generate_ngrams(tokenized_sentences, n):
    # Flatten the list of tokenized sentences into a single list of words
    tokens = [word for sentence in tokenized_sentences for word in sentence]
    n_grams = list(ngrams(tokens, n))
    return [" ".join(gram) for gram in n_grams] #make them strings and change back to a tuple for model training

# Generate bigrams and trigrams using the already tokenized text
df['nltk_unigrams'] = df['tokenized_text'].apply(lambda x: generate_ngrams(x, 1))
df['nltk_bigrams'] = df['tokenized_text'].apply(lambda x: generate_ngrams(x, 2))
df['nltk_trigrams'] = df['tokenized_text'].apply(lambda x: generate_ngrams(x, 3))

print(df)

"""###Frequency Analysis

useful links: https://ecampusontario.pressbooks.pub/nudh3/chapter/implementing-and-analyzing-n-grams-in-python/

https://docs.python.org/3/library/collections.html collections
https://docs.python.org/3/library/itertools.html itertools
"""

# Frequency analysis and visualization
from collections import Counter
import itertools

# Flatten the list of lists for each n-gram column before counting
unigram_list = list(itertools.chain.from_iterable(df['nltk_unigrams']))
bigram_list = list(itertools.chain.from_iterable(df['nltk_bigrams']))
trigram_list = list(itertools.chain.from_iterable(df['nltk_trigrams']))


# Count the frequency of each n-gram
unigram_counts = Counter(unigram_list)
bigram_counts = Counter(bigram_list)
trigram_counts = Counter(trigram_list)

# Convert the counts to a DataFrame for easier analysis and sorting
unigram_frequency_df = pd.DataFrame(unigram_counts.items(), columns=['N-gram', 'Frequency'])
bigram_frequency_df = pd.DataFrame(bigram_counts.items(), columns=['N-gram', 'Frequency'])
trigram_frequency_df = pd.DataFrame(trigram_counts.items(), columns=['N-gram', 'Frequency'])

# Sort by frequency in descending order
unigram_frequency_df = unigram_frequency_df.sort_values(by='Frequency', ascending=False).reset_index(drop=True)
bigram_frequency_df = bigram_frequency_df.sort_values(by='Frequency', ascending=False).reset_index(drop=True)
trigram_frequency_df = trigram_frequency_df.sort_values(by='Frequency', ascending=False).reset_index(drop=True)

#create top-10's for each n-gram to visualize later
top_unigrams = unigram_frequency_df.head(10)
top_bigrams = bigram_frequency_df.head(10)
top_trigrams = trigram_frequency_df.head(10)

# Print the top N most frequent n-grams
print("Top 10 most frequent unigrams:")
print(top_unigrams)
print("\nTop 10 most frequent bigrams:")
print(top_bigrams)
print("\nTop 10 most frequent trigrams:")
print(top_trigrams)

"""###visualizing n-gram frequency distribution using matplotlib and word cloud"""

#unigram Barplot
import matplotlib.pyplot as plt
import numpy as np

plt.bar(top_unigrams['N-gram'], top_unigrams['Frequency'])
plt.title('Unigram Frequencies')
plt.xlabel('N-grams')
plt.ylabel('Frequency')
plt.xticks(rotation=90)
plt.show()

#Bigram Barplot
import matplotlib.pyplot as plt
import numpy as np

plt.bar(top_bigrams['N-gram'], top_bigrams['Frequency'])
plt.title('Bigram Frequencies')
plt.xlabel('N-grams')
plt.ylabel('Frequency')
plt.xticks(rotation=90)
plt.show()

#Bigram Barplot
import matplotlib.pyplot as plt
import numpy as np

plt.bar(top_trigrams['N-gram'], top_trigrams['Frequency'])
plt.title('Trigram Frequencies')
plt.xlabel('N-grams')
plt.ylabel('Frequency')
plt.xticks(rotation=90)
plt.show()

"""###Word Cloud Visualizations"""

from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

unigram_text = ' '.join(unigram_frequency_df['N-gram'].astype(str).tolist()) #word cloud only takes lists so we create a list out of the 'N-gram' column

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(unigram_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Unigram Word Cloud")
plt.show()

"""# Task 2
In this task we will be preparing our dataset for training in a model

## Spliting the Dataset
This was a useful link: https://www.geeksforgeeks.org/machine-learning/how-to-split-a-dataset-into-train-and-test-sets-using-python/
"""

from sklearn.model_selection import train_test_split

X = df['tokenized_text']


X_train, X_test = train_test_split(X, test_size=0.2, random_state=42) #Set test set size to 0.2 for 20% in test set and Random_state to set the seed for reproducibility

X_train = X_train.apply(lambda x: x[0])
X_test  = X_test.apply(lambda x: x[0])

X_train.head(30)

#change back to dataframe from series for ease of use and manipulation
train = pd.DataFrame(X_train)
test = pd.DataFrame(X_test)
print(train.head(30))

def generate_ngrams(tokens, n):
    return list(ngrams(tokens, n))

# Generate bigrams and trigrams using the already tokenized text
train['unigrams'] = train['tokenized_text'].apply(lambda x: generate_ngrams(x, 1))
train['bigrams'] = train['tokenized_text'].apply(lambda x: generate_ngrams(x, 2))
train['trigrams'] = train['tokenized_text'].apply(lambda x: generate_ngrams(x, 3))

test['unigrams'] = test['tokenized_text'].apply(lambda x: generate_ngrams(x, 1))
test['bigrams'] = test['tokenized_text'].apply(lambda x: generate_ngrams(x, 2))
test['trigrams'] = test['tokenized_text'].apply(lambda x: generate_ngrams(x, 3))

print(train)

#create lists, generate counts, and calculate frequencies for test and train set

# Flatten the list of lists for each n-gram column before counting
train_unigram_list = list(itertools.chain.from_iterable(train['unigrams']))
train_bigram_list = list(itertools.chain.from_iterable(train['bigrams']))
train_trigram_list = list(itertools.chain.from_iterable(train['trigrams']))

#test set
test_unigram_list = list(itertools.chain.from_iterable(test['unigrams']))
test_bigram_list = list(itertools.chain.from_iterable(test['bigrams']))
test_trigram_list = list(itertools.chain.from_iterable(test['trigrams']))

# Count the frequency of each n-gram
train_unigram_counts = Counter(train_unigram_list)
train_bigram_counts = Counter(train_bigram_list)
train_trigram_counts = Counter(train_trigram_list)

#test set
test_unigram_counts = Counter(test_unigram_list)
test_bigram_counts = Counter(test_bigram_list)
test_trigram_counts = Counter(test_trigram_list)

# Convert the counts to a DataFrame for easier analysis and sorting
train_unigram_frequency_df = pd.DataFrame(train_unigram_counts.items(), columns=['N-gram', 'Frequency'])
train_bigram_frequency_df = pd.DataFrame(train_bigram_counts.items(), columns=['N-gram', 'Frequency'])
train_trigram_frequency_df = pd.DataFrame(train_trigram_counts.items(), columns=['N-gram', 'Frequency'])

#test set
test_unigram_frequency_df = pd.DataFrame(test_unigram_counts.items(), columns=['N-gram', 'Frequency'])
test_bigram_frequency_df = pd.DataFrame(test_bigram_counts.items(), columns=['N-gram', 'Frequency'])
test_trigram_frequency_df = pd.DataFrame(test_trigram_counts.items(), columns=['N-gram', 'Frequency'])

print(test_unigram_list)
print(test_bigram_list)
print(test_trigram_list)

"""###Creating Unigram, Bigram and Trigram predictive models
docs: https://www.nltk.org/api/nltk.lm.api.html

"""

#unigram models
from nltk.probability import FreqDist
from nltk.lm.preprocessing import padded_everygram_pipeline
from nltk.lm import MLE
import itertools

# Use the original tokenized sentences from X_train as a list of lists for the unigram pipeline
unigram_train_data, unigram_padded_vocab = padded_everygram_pipeline(1, X_train.tolist())

# Flatten X_train completely to a list of strings
X_train_flat_words = [word for doc in X_train for sentence in doc for word in sentence]

# Calculate FreqDist directly on the flattened list of words
freq_dist_unigrams = FreqDist(X_train_flat_words)


unigramlanguagemodel = MLE(1)
unigramlanguagemodel.fit(unigram_train_data, unigram_padded_vocab)

print(unigramlanguagemodel.generate(1)) #text seed not necessary

#Bigram model
bigram_train_data, bigram_padded_vocab = padded_everygram_pipeline(2, train_bigram_list)

freq_dist_bigrams = FreqDist(train_bigram_list)

bigramlanguagemodel = MLE(2)
bigramlanguagemodel.fit(bigram_train_data, bigram_padded_vocab)

print(bigramlanguagemodel.generate(1, text_seed=['company', 'makes']))

#trigram model
trigram_train_data, trigram_padded_vocab = padded_everygram_pipeline(3, train_trigram_list)

freq_dist_trigrams = FreqDist(train_trigram_list)

trigramlanguagemodel = MLE(3)
trigramlanguagemodel.fit(trigram_train_data, trigram_padded_vocab)

print(trigramlanguagemodel.generate(1, text_seed=['company', 'makes']))

"""### Generating Conditional Probabilities
this thread was useful: https://stackoverflow.com/questions/38068539/finding-conditional-probability-of-trigram-in-python-nltk

we do this by counting n-grams and their preceding contexts
don't need to do this for unigrams because their probabilites are just their number of occurences compared to the entire corpus, but I will still show it.

Note: I wrote this before realizing that I actually train a model
"""

#Unigram probabilities
from nltk.probability import FreqDist

fdist = FreqDist(train_unigram_list)# we use the version we created into a list
for word, count in fdist.items():
    total_unigrams = len(train_unigram_list) #generates the total number of unigrams
    probability = count / total_unigrams
    print(f"P({word}) = {probability:.4f}")

#bigram conditional probabilities
from nltk.probability import ConditionalFreqDist, ConditionalProbDist, MLEProbDist

cfdist_bigrams = ConditionalFreqDist(train_bigram_list)

cpdist_bigrams = ConditionalProbDist(cfdist_bigrams, MLEProbDist) # use their Maximum likelihood estimation functions

#now we can apply this to any 2 words we'll use "company" and "makes" as an example

prob_makes_given_company = cpdist_bigrams['company'].prob('makes')
print(f"P(makes | company) = {prob_makes_given_company:.4f}")

# and we can get the probility of all words compared to a single word

for word in cpdist_bigrams['company'].samples():
    prob = cpdist_bigrams['company'].prob(word)
    print(f"P({word} | company) = {prob:.4f}")

#trigrams

condition_pairs = [((w0, w1), w2) for w0, w1, w2 in train_trigram_list]

cfdist_trigrams = ConditionalFreqDist(condition_pairs)

cpdist_trigrams = ConditionalProbDist(cfdist_trigrams, MLEProbDist)

#probability of an example trigram
prob_money_given_company_makes = cpdist_trigrams[('company', 'makes')].prob('money')
print(f"P(money | company, makes) = {prob_money_given_company_makes:.4f}")


for word in cpdist_trigrams[('company', 'makes')].samples():
    prob = cpdist_trigrams[('company', 'makes')].prob(word)
    print(f"P({word} | company, makes) = {prob:.4f}")

"""## Calculating Perplexity
useful links: https://stackoverflow.com/questions/54941966/how-can-i-calculate-perplexity-using-nltk

I utilized NLTK's native perplexity function for ease of use
"""

#unigram perplexity using NLTK's native perplexity function
unigramlanguagemodel.perplexity(test_unigram_list)

bigramlanguagemodel.perplexity(test_bigram_list)

trigramlanguagemodel.perplexity(test_trigram_list)

"""The conclusion can be that like in the text book our data is not as comprehensive and we need to replace 0s. Or I did something very wrong

#Task 3 Handling Unseen N-grams

## Laplace Smoothing
This will make it so our model assigns non-zeroes so that our perplexity won't be infinity

simple stack overflow explanation: https://stackoverflow.com/questions/60631437/laplace-smoothing-function-in-nltk
"""

from nltk.lm import Laplace
from nltk.lm.preprocessing import padded_everygram_pipeline
import itertools

n=1

laplace_unigram_train_data, laplace_unigram_padded_vocab = padded_everygram_pipeline(n, [list(itertools.chain.from_iterable(sentence)) for sentence in train])

laplaceunigramlanguagemodel = Laplace(n)
laplaceunigramlanguagemodel.fit(laplace_unigram_train_data, laplace_unigram_padded_vocab)

perplexity_score = laplaceunigramlanguagemodel.perplexity(test_unigram_list)
print(f"Unigram Laplace Model Perplexity: {perplexity_score}")

from nltk.lm import Laplace
from nltk.lm.preprocessing import padded_everygram_pipeline
import itertools

n=2

laplace_bigram_train_data, laplace_bigram_padded_vocab = padded_everygram_pipeline(n, [list(itertools.chain.from_iterable(sentence)) for sentence in train])

laplacebigramlanguagemodel = Laplace(n)
laplacebigramlanguagemodel.fit(laplace_bigram_train_data, laplace_bigram_padded_vocab)

perplexity_score = laplacebigramlanguagemodel.perplexity(test_bigram_list)
print(f"bigram Laplace Model Perplexity: {perplexity_score}")

from nltk.lm import Laplace
from nltk.lm.preprocessing import padded_everygram_pipeline
import itertools

n=3

laplace_trigram_train_data, laplace_trigram_padded_vocab = padded_everygram_pipeline(n, [list(itertools.chain.from_iterable(sentence)) for sentence in train])

laplacetrigramlanguagemodel = Laplace(n)
laplacetrigramlanguagemodel.fit(laplace_trigram_train_data, laplace_trigram_padded_vocab)

perplexity_score = laplacetrigramlanguagemodel.perplexity(test_trigram_list)
print(f"trigram Laplace Model Perplexity: {perplexity_score}")

"""### Critical Analysis
an amazing improvement from using MLE. because the training corpus isn't big enough all word/word combination might be a zero probability making it so that perplexity becomes infinity. with laplace we add 1 to each probability even if that token is never seen. I find it interesting that perplexity plateaus after the 2-gram model with perplexity being almost equal in the trigram, would be cool to see how it does with a quadrigram. by exploring other smoothing techniques we could see measured improvement in the different n-gram models

#Task 4: Interpolation

In this task we will combine models utilizing linear interpolation with predetermined weights which should decrease perplexity by creating a unified model out of all three
"""

#0.7,0.2,0.1 weights
#werre going to take the models with laplace smoothing applied and create a function that calculates probabilities for each ngram model and multiplies them by our weights or in this function lambdas
def interpolated_prob(word, context, lambdas=(0.7,0.2,0.1)):
    l1, l2, l3 = lambdas
    p_uni = laplaceunigramlanguagemodel.score(word)
    p_bi = laplacebigramlanguagemodel.score(word, context[-1:]) if len(context) >= 1 else 0
    p_tri = laplacetrigramlanguagemodel.score(word, context[-2:]) if len(context) >= 2 else 0
    return l1*p_uni + l2*p_bi + l3*p_tri

#Now we can apply this function to our test set and calculate perplexity
context = ["the", "company"] #provide words that come before the word we want to check probaility for
print(interpolated_prob("makes", context, lambdas=(0.2, 0.3, 0.5)))

"""Techinically this is not a model ^^^ so to calculate perplexity will be harder because we can't use .perplexity like we did before. it will be a little hard, but we'll try

Essentially were going to iterate a form of the above function over the entire test set, accumulate log probabilities and compute the perplexity using a  function
"""

import math

def interpolated_perplexity(tokenized_sentences, lambdas=(0.7,0.2,0.1), epsilon=1e-12):

    log_prob_sum = 0.0
    N = 0
    max_order = 3  # since we use unigram, bigram, trigram you would scale this up with more n gram models

    for sent in tokenized_sentences:
        for i, word in enumerate(sent):#these first two lines iterate over sentences then words
            start = max(0, i - (max_order - 1)) #this determines context
            context = sent[start:i]
            p = interpolated_prob(word, context, lambdas=lambdas)#this uses the function from before to get the interpolated proabilities
            p = max(p, epsilon)
            log_prob_sum += math.log(p)
            N += 1 # last two lines accumulate the log probailities

    perplexity = math.exp(-log_prob_sum / N) if N > 0 else float("inf") #this is the formula for perplexity
    return perplexity

pp_score = interpolated_perplexity(test, lambdas=(0.7,0.2,0.1))#we use the original test set cause we need the full tokenized sentences
print(f"Interpolated Model Perplexity: {pp_score}")

"""### Interpolated Model Analysis

We find that the perplexity of the interpolated "model" is better than a single model by it self. interpolated models are better because it can fallback on the reliability of the lower-order models while still providing flexibility. although the perplexity is only slightly lower this improvement can still be seen when attempting to make predictions
"""